FLUXO 

	1 - ESCOLHA DA ORIGEM E DESTINO

		AUTOMATIZADO (<>)

	2 - ESCOLHA DO TIPO DA MERCADORIA QUE VAI SER ENVIADO				
			
		SISTEMA 

			CADASTRO DE TIPO DE PRODUTOS (INFORMATIVO)				
				=> DOCUMENTOS

			CADASTRO DE SERVIÇOS
                => NOME
				=> ALTURA
				=> LARGURA
				=> CUMPRIMENTO
				=> PESO

		2.1 - ESCOLHA DOS SERVIÇOS APÓS DIGITAR OS ATIBUTOS DO PRODUTO

        LARGURA 
        ALTURA
        CUMPRIMENTO
        PESO
        VALOR DECLARADO
        
        LARGURA X ALTURA X CUMPRIMENTO / 30000
