/**
 * S.M.A.R.T Minerador
 * Documentação da Api do WS do S.M.A.R.T Minerador
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Historico } from './historico';
import { Grupo } from './grupo';


export interface DadosTeste {
    dadosTesteAcuracia?: number;
    dadosTesteSchemaMatriz?: string;
    dadosTesteSchemaResult?: string;
    dadosTesteTabelaMatriz?: string;
    dadosTesteTabelaResult?: string;
    dadosTesteUltimo?: number;
    dadosTestePercentual?: number;
    historico?: Historico;
    historicoId?: number;
    acuraciaMedia?: number;
    grupo?: Grupo;
}
