/**
 * S.M.A.R.T Minerador
 * Documentação da Api do WS do S.M.A.R.T Minerador
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Atributo } from './atributo';
import { Grupo } from './grupo';
import { Pasta } from './pasta';
import { FonteOrigem } from './fonteOrigem';


export interface Fonte {
    atributos?: Array<Atributo>;
    fonteAlias?: string;
    fonteArquivo?: string;
    fonteId?: number;
    fonteNome?: string;
    fonteSchema?: string;
    fonteStatusProc?: string;
    fonteTipo?: string;
    grupos?: Array<Grupo>;
    pastas?: Array<Pasta>;
    fonteData?: Date;
    fonteErroCriacao?: string;
    origem?: FonteOrigem;
    fonteTotalRegistros?: number;
    fonteAprendizado?: boolean;
}
