/**
 * S.M.A.R.T Minerador
 * Documentação da Api do WS do S.M.A.R.T Minerador
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { FuncaoMineracaoAlgoritmo } from './funcaoMineracaoAlgoritmo';
import { Modelo } from './modelo';
import { Parametro } from './parametro';


export interface FuncaoMineracao {
    funcaoMineracaoAlgoritmos?: Array<FuncaoMineracaoAlgoritmo>;
    funcaoMineracaoAlias?: string;
    funcaoMineracaoId?: number;
    funcaoMineracaoNomeInterno?: string;
    funcaoMineracaoSeparaDados?: boolean;
    modelos?: Array<Modelo>;
    parametros?: Array<Parametro>;
    algortimosAlias?: Array<string>;
    funcaoMineracaoSeparaDadosLabel: string;

}
