/**
 * S.M.A.R.T Minerador
 * Documentação da Api do WS do S.M.A.R.T Minerador
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AtributoGrupo } from './atributoGrupo';
import { Fonte } from './fonte';
import { Modelo } from './modelo';
import { Regra } from './regra';
import { Usuario } from './usuario';


export interface Grupo {
    atributoGrupos?: Array<AtributoGrupo>;
    fonte?: Fonte;
    grupoData?: Date;
    grupoId?: number;
    grupoNome?: string;
    grupoObjetivo?: string;
    grupoSchema?: string;
    grupoStatusProc?: string;
    grupoTabela?: string;
    grupoVisibilidade?: number;
    modelos?: Array<Modelo>;
    regras?: Array<Regra>;
    usuario?: Usuario;
    grupoErroCriacao?: string;
    grupoTotalRegistros?: number;
    porcentagemRegistrosFonte?: number;
}
