/**
 * S.M.A.R.T Minerador
 * Documentação da Api do WS do S.M.A.R.T Minerador
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Parametro } from './parametro';
import { ParametroModelo } from './parametroModelo';


export interface OpcaoParametro { 
    opcaoParametroAlias?: string;
    opcaoParametroId?: number;
    opcaoParametroNome?: string;
    parametro?: Parametro;
    parametroModelos?: Array<ParametroModelo>;
}
