/**
 * S.M.A.R.T Minerador
 * Documentação da Api do WS do S.M.A.R.T Minerador
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Atributo } from './atributo';
import { Modelo } from './modelo';
import { OpcaoParametro } from './opcaoParametro';
import { Parametro } from './parametro';


export interface ParametroModelo { 
    atributo?: Atributo;
    modelo?: Modelo;
    opcaoParametro?: OpcaoParametro;
    parametro?: Parametro;
    parametroModeloId?: number;
    parametroModeloValor?: string;
}
