/**
 * S.M.A.R.T Minerador
 * Documentação da Api do WS do S.M.A.R.T Minerador
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Algoritmo } from './algoritmo';
import { FuncaoMineracao } from './funcaoMineracao';
import { OpcaoParametro } from './opcaoParametro';
import { ParametroModelo } from './parametroModelo';


export interface Parametro {
    algoritmo?: Array<Algoritmo>;
    funcaoMineracao?: Array<FuncaoMineracao>;
    listaAlgoritmos?: string[];
    listaFuncoes?: string[];
    opcaoParametros?: Array<OpcaoParametro>;
    parametroAlias?: string;
    parametroId?: number;
    parametroMaximo?: number;
    parametroMinimo?: number;
    parametroModelos?: Array<ParametroModelo>;
    parametroNome?: string;
    parametroObrigatorio?: boolean;
    parametroOrigem?: string;
    parametroTipo?: string;
    parametroVisivel?: boolean;
    parametroOrigemDescricao?: string;
    parametroTipoDescricao?: string;
}
