/**
 * S.M.A.R.T Minerador
 * Documentação da Api do WS do S.M.A.R.T Minerador
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Atributo } from './atributo';
import { Fonte } from './fonte';


export interface Pasta { 
    atributos?: Array<Atributo>;
    fonte?: Fonte;
    pastaId?: number;
    pastaNome?: string;
    pastaOrdem?: number;
    pastaPai?: Pasta;
}
