/**
 * S.M.A.R.T Minerador
 * Documentação da Api do WS do S.M.A.R.T Minerador
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Atributo } from './atributo';
import { Grupo } from './grupo';


export interface Regra {
    atributo?: Atributo;
    grupo?: Grupo;
    regraData?: Date;
    regraId?: number;
    regraOperadorLogico?: string;
    regraOperadorRelacional?: string;
    regraOrdem?: number;
    regraValorComparado?: string;
    regraRaiz?: Regra;
    regras?: Regra[];
}
