/**
 * S.M.A.R.T Minerador
 * Documentação da Api do WS do S.M.A.R.T Minerador
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Grupo } from './grupo';
import { Historico } from './historico';
import { Modelo } from './modelo';


export interface Usuario {
    grupos?: Array<Grupo>;
    historicos?: Array<Historico>;
    modelos?: Array<Modelo>;
    usuarioCpf?: string;
    usuarioEmail?: string;
    usuarioId?: number;
    usuarioLogin?: string;
    usuarioMatricula?: string;
    usuarioNome?: string;
    usuarioSenha?: string;
    token?: string;
}
